[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
object = { version = "0.36.3", default-features = false, features = ["std", "read", "macho"] }
shared = { path = "../shared" }
